### ISSUE TITLE
List of embedded resources with only one element

### ISSUE THREAD

**Issue by jonathanschein** [daxnet/hal#2]
When generating a Json HAL with a list of two or more embedded resources (like orders example), the library returns an array of embedded objects: 

`{
  "_links": {
    "self": {
      "href": "/orders"
    },
    "curies": [
      {
        "name": "ea",
        "href": "http://example.com/docs/rels/{rel}",
        "templated": true
      }
    ],
    "next": {
      "href": "/orders?page=2"
    },
    "ea:find": {
      "href": "/orders{?id}",
      "templated": true
    }
  },
  "currentlyProcessing": 14,
  "shippedToday": 20,
  "_embedded": {
    "ea:order": [
      {
        "_links": {
          "self": {
            "href": "/orders/123"
          },
          "ea:basket": {
            "href": "/baskets/98712"
          },
          "ea:customer": {
            "href": "/customers/7809"
          }
        },
        "total": 30.0,
        "currency": "USD",
        "status": "shipped"
      },
      {
        "_links": {
          "self": {
            "href": "/orders/124"
          },
          "ea:basket": {
            "href": "/baskets/97213"
          },
          "ea:customer": {
            "href": "/customers/12369"
          }
        },
        "total": 20.0,
        "currency": "USD",
        "status": "processing"
      }
    ]
  }
}`

but when the list has only one element, the library returns an embedded object instead of an array with only one element:

`{
  "_links": {
    "self": {
      "href": "/orders"
    },
    "curies": [
      {
        "name": "ea",
        "href": "http://example.com/docs/rels/{rel}",
        "templated": true
      }
    ],
    "next": {
      "href": "/orders?page=2"
    },
    "ea:find": {
      "href": "/orders{?id}",
      "templated": true
    }
  },
  "currentlyProcessing": 14,
  "shippedToday": 20,
  "_embedded": {
    "ea:order": {
      "_links": {
        "self": {
          "href": "/orders/123"
        },
        "ea:basket": {
          "href": "/baskets/98712"
        },
        "ea:customer": {
          "href": "/customers/7809"
        }
      },
      "total": 30.0,
      "currency": "USD",
      "status": "shipped"
    }
  }
}`

I think it sholud return an array with one order, to be consistent with the previous result. ¿Is there any way to force the API to generate an array with one object instead?

Those Json Hal examples were generated using then Example test.

Thanks in advance!

**Comment by daxnet** [comment]
@jonathanschein Great catch! I am working on this right now. Will give you the update.

**Comment by daxnet** [comment]
@jonathanschein Your request has been fixed and you should be able to see that in the 1.0.14 build of the Hal library from Nuget. When using the `AddEmbedded` on the Fluent API, or when you create a new `EmbeddedResourceCollection` instance by using its constructor, you should be able to specify an optional parameter, `enforcingArrayConverting`, when set to `true`, will always create an array no matter how many states are in the embedded resource.

**Comment by jonathanschein** [comment]
@daxnet , thanks, I tried the solution, but I can't generate something like the following example:

`{
  "_links": {
    "self": {
      "href": "/oneModel/1"
    }
  },
  "prop_a": 100,
  "prop_b": "test",
  "id": 1,
  "_embedded": {
    "items": [
      {
        "_links": {
          "self": {
            "href": "/SimpleModels/1"
          }
        },
        "descripcion": "d",
        "cantidad_total": 10,
        "enumerado": "A",
        "id": 1
      },
      {
        "_links": {
          "self": {
            "href": "/SimpleModels/2"
          }
        },
        "descripcion": "dd",
        "cantidad_total": 20,
        "enumerado": "B",
        "id": 2
      },
      {
        "_links": {
          "self": {
            "href": "/SimpleModels/3"
          }
        },
        "descripcion": "ddd",
        "cantidad_total": 30,
        "enumerado": "C",
        "id": 3
      }
    ],
	"oneEntity": {
		"_links": {
          "self": {
            "href": "/oneEntity/1"
          }
        },
        "descripcion": "this is one entity",
        "name": "ABC",
        "id": 1
	}
  }
}`

Under the embedded list,  I would like to have collections and embeded resources to represent a class like the following:

public class OneModel
{
   public int Id {get: set:}
  public int PropA {get; set;}
  public string PropB {get; set;}
   public IList<SimlpeModel> items {get; set;}
   public OtherModel oneEntity {get: set: }
}

Maybe, instead of `EmbeddedResourceCollection`, the instance of `EmbeddedResource` should have the 
`enforcingArrayConverting` parameter, to define how to render the resource collection.

thanks again!

**Comment by daxnet** [comment]
@jonathanschein Sorry I just missed your comments above. I will try to investigate your case during these two days and give you the answer.

**Comment by daxnet** [comment]
As the changes have been merged, will close this issue.
