### ISSUE TITLE
The library doesn't support serializing enums as strings

### ISSUE THREAD

**Issue by AleksandrKuznetsovEF** [daxnet/hal#24]
If resource is built from type that contains any enum, the result json will contain the integer value of the enum rather than its string name. Unfortunately, this behaviour can not be fixed by any settings in the application. According to my investigation, the reason of such behaviour is the fact that there is no way to setup `JsonSerializerSettings` field in `SupportsHalAttribute` and `converters` field in `Resource` class.

I tried to fix it in the fork by adding `StringEnumConverter` to converters and it resolved the issue.

Is it possible to make these fields configurable outside?

**Comment by daxnet** [comment]
PR has been merged, close this ticket.
