### ISSUE TITLE
Add support of .NET 6 to Hal.AspNetCoreIntegration

### ISSUE THREAD

**Issue by AleksandrKuznetsovEF** [daxnet/hal#28]
Previously we used version 2.1.4 of Hal.AspNetCoreIntegration that supported .NET 6, but now we need to use a fresh one (2.2.0) that supports serializer configuration and unfortunately compatible with .NET 7 and .NET 8 only.
Is there is chance to add support of .NET 6 also?

**Comment by daxnet** [comment]
Hi @AleksandrKuznetsovEF ,
I have added back the support to .NET 6, please use the version v2.2.1.
Thanks.
