### ISSUE TITLE
Ability to add multiples resources with fluent API

### ISSUE THREAD

**Issue by kevingeorget** [daxnet/hal#31]
Hello @daxnet !
First of all, thank you for this library  (:

From the  `IEmbeddedResourceBuilder`, the fluent API seems to expose a Resource method that only accepts one `ResourceBuilder` as argument: 
```cs
var resource = new ResourceBuilder()
            .WithState(new { count = 4 })
            .AddSelfLink()
            .WithLinkItem(
                $"{Configuration.AppBaseUrl()}/{Endpoints.MyRaceEvents}",
                "Race Events Registrations"
            )
            .AddEmbedded("raceEventRegistrations")
            .Resource(new ResourceBuilder().WithState(new {id = 1}))
            .Resource(new ResourceBuilder().WithState(new {id = 2}))
            .Resource(new ResourceBuilder().WithState(new {id = 3}))
            .Resource(new ResourceBuilder().WithState(new {id = 4}))
            .Build();
``` 
            
Let's say i have a collection of entities i want to embed to the Hal resource. 
I can't achieve an elegant way to simply add several resources to my embedded resource collection from a list. 

I'd like to achieve something like this : 
```cs 
var resource = new ResourceBuilder()
            .WithState(new { count = registrations.Count })
            .AddSelfLink()
            .WithLinkItem(
                $"{Configuration.AppBaseUrl()}/{Endpoints.MyRaceEvents}",
                "Race Events Registrations"
            )
            .AddEmbedded("raceEventRegistrations")
            .Resources(
                registrations.Select(r => new ResourceBuilder().WithState(new { id = r.Id }))
            )
            .Build();
```
            
Did I miss something ?

Thank you in advance

**Comment by LucaJakob** [comment]
Consider the following approach:

```cs
var resource = new ResourceBuilder()
    .WithState(new { count = registrations.Count() })
    .AddSelfLink().WithLinkItem(
        $"{Configuration.AppBaseUrl()}/{Endpoints.MyRaceEvents}",
            "Race Events Registrations"
    )
    .AddEmbedded("raceEventRegistrations", true); // force array conversion
    
foreach (var reg in registrations)
{
    resource = resource
        .Resource(new ResourceBuilder().WithState(new { id = reg.Id })
        // ensure IEmbeddedResourceItemBuilder is cast back to IEmbeddedResourceBuilder
        .AddEmbedded("raceEventRegistrations", true);
}

resource.Build();
```

I think your suggestion is an elegant solution, but hopefully this will do in the meantime.

**Comment by daxnet** [comment]
@kevingeorget and @LucaJakob 
Thank you for the great feedback, I will review your request and considering a fix.
In the meanwhile, you can also folk this repo and create a PR, lets collaborate.
Thanks!

**Comment by daxnet** [comment]
Hi @LucaJakob , I reviewed your PR and understood the scenario, I have modified some of your edits and made it compatible with the current design. Changes' been merged to main branch and a new version 2.2.2 has been released. This release also included .NET 9 support. Thank you for your collaboration and wonderful work.

**Comment by LucaJakob** [comment]
Hey @daxnet , thanks for implementing the change! I can use it in my project as well now. I checked out the commit and the changes make sense.

However, your [nginx.conf file](https://github.com/daxnet/hal/blob/700ccd249c39b79c9804fbf3be90c2d2069172ae/example/Hal.Nginx/nginx.conf#L11) and the [README.md version](https://github.com/daxnet/hal/blob/700ccd249c39b79c9804fbf3be90c2d2069172ae/README.md?plain=1#L289) are now different. Should I open an Issue about it?

**Comment by daxnet** [comment]
@LucaJakob , yes, please, you made a great point! So glad to see that you can use it now. :)
