### ISSUE TITLE
Ability to enforce Array Conversion on Link Relation with Builder API

### ISSUE THREAD

**Issue by LucaJakob** [daxnet/hal#35]
The current state of the `.AddLink(string rel)` method is that it only accepts the relation's name. If this method is called more than once with the same relation, it will convert the value to an array.

Internally, it [sets enforcingArrayConverting to false by default](https://github.com/daxnet/hal/blob/f652123418b7b2c3687e8874691739911d66a23b/src/Hal/Builders/Extensions.cs#L68). However, as the HAL specification states:

[Mike Kelly Internet Draft 11, Section 4.1.1](https://www.ietf.org/archive/id/draft-kelly-json-hal-11.html#section-4.1.1)
> For a given link relation, servers SHOULD NOT change the property between a Link Object and array of Link Objects. Such changes SHOULD introduce a new link relation. This is to avoid breaking changes for existing clients coupled to the original choice, and is a consideration for any JSON based API.

For relations where link objects can range from 1..N, there should be a way to enforce array converting.

To avoid backwards incompatibility, the method could be rewritten as `.AddLink(string rel, bool enforceArrayConverting = false)`.

**Comment by daxnet** [comment]
@LucaJakob I will take a look and make a PR

**Comment by daxnet** [comment]
@LucaJakob 
Sorry for the delayed response (quite busy these days). Could you please help review the PR below?
https://github.com/daxnet/hal/pull/36
Let me know if it addressed the issue you've requested.
Thank you.

**Comment by LucaJakob** [comment]
Sure, I can check it later today. Thanks for addressing the FR.

**Comment by daxnet** [comment]
@LucaJakob New release 2.2.3 should address this.
